AWSTemplateFormatVersion: 2010-09-09
Description: Basic AWS Infrastructure for deployment
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    # CreationPolicy: # <--- creation policy with timeout of 5 minutes
    #   ResourceSignal:
    #     Timeout: PT1M    
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: personal-east-ansible
      ImageId: ami-04505e74c0741db8d #Ubuntu Server 20.04 LTS (HVM), SSD Volume Type
      InstanceType: t3.micro 
      # UserData:
      #   Fn::Base64: !Sub |
      #     #!/bin/bash
      #     sudo apt-get update -y
      #     sudo mkdir -p /opt/aws/bin
      #     sudo wget https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
      #     sudo python3 -m easy_install --script-dir /opt/aws/bin aws-cfn-bootstrap-py3-latest.tar.gz
      #     sudo /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}
      # UserData: !Base64 
      #   'Fn::Sub':
      #     - >
      #       #!/bin/bash -xe
      #       sudo apt-get update -y
      #       sudo mkdir -p /opt/aws/bin
      #       wget https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
      #       sudo python3 -m easy_install --script-dir /opt/aws/bin aws-cfn-bootstrap-py3-latest.tar.gz
      #       # Install the files and packages from the metadata
      #       sudo /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2Instance --region us-east-1
      #       # Signal the status from cfn-init
      #       sudo /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2Instance --region us-east-1
      #     - {}               
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
Outputs:
  PublicIp:
    Value:
      Fn::GetAtt:
        - EC2Instance
        - PublicIp
    Export:
      Name: PublicIp
    Description: EC2Instance's PublicIp Address