version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
  # python: circleci/python@1.5.0
commands:
  destroy_infra:
    steps:
      - run:
          name: Destroy Aws infra
          when: on_fail
          command: |
            aws cloudformation delete-stack \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}
  update_inventory:
    steps:
      - run:
          name: create inventory file
          command: |
            echo "[all]" > inventory
      - run:
          name: update inventory with ips
          command: |
            aws cloudformation describe-stacks \
                --query 'Stacks[0].Outputs[?OutputKey==`PublicIp`].OutputValue'  \
                --output text >> inventory
      - run:
          name: list inventory file
          command: |
            cat inventory
      - persist_to_workspace:
          root: .
          paths: 
            - .
jobs:
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Install tar utility
            command: |
              yum install -y tar gzip        
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
        - destroy_infra
        - run:
            name: Take a nap while instance intializes
            command: |
              sleep 1m        
        - update_inventory
        - run:
            name: check per2
            command: |
              cat inventory        
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints: ["a3:00:a7:22:fc:4a:5b:50:bb:ec:37:72:60:67:bc:96"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt awsdeploy.yml
      - destroy_infra
workflows:
  on_commit:
    jobs:
      - create_infrastructure
      - configure_infrastructure:
           requires:
            - create_infrastructure

